version = "1.0"

[main]
name = "Settings"

    [main.is_signup]
    name = "Signup configuration"

    services = ["__APP__"]

        [main.is_signup.is_signup]
        ask = "Allow signups?"
        type = "boolean"
        yes = '1'
        no = ''
        help = "Would you like to allow visitors to register and create an account?"
        bind = "signup:/var/www/__APP__/server.js"
