version = "1.0"
name= "Armadietto configuration panel"

[main]
name = "Armadietto signup configuration"

    [main.is_signup]
    name = "Signup configuration"

        [main.is_signup.signup]
        ask.en = "Allow signups?"
        ask.fr = "Accepter les inscriptions ?"
        type = "boolean"
        default = true
        help.en = "Would you like to allow visitors to register and create an account?"
        help.fr = "Souhaitez-vous autoriser les visiteurs à s'inscrire et créer un compte ?"    
