version = "1.0"

[main]
name = "Settings"

    [main.global_config]
    name = "Access options"

    services = ["nginx", "__APP__"]

        [main.global_config.is_signup]
        ask = "Allow signups?"
        type = "boolean"
        help = "Would you like to allow visitors to register and create an account?"
        bind = "signup:__FINALPATH__/server.js"
