version = "1.0"

[main]
name = "Armadietto configuration"

    [main.global_config]
    name = "Access options"
    services = ["nginx", "__APP__"]

        [main.global_config.is_signup]
        ask = "Allow signups?"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Would you like to allow visitors to register and create an account?"
        bind = "signup:__FINALPATH__/server.js"
