#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "armadietto"
name = "Armadietto"
description.en = "RemoteStorage server running as a nodejs web service with systemd"
description.fr = "Serveur remoteStorage excécuté en tant que service web nodejs par systemd"

version = "0.6.0~ynh1"

maintainers = ["bencharp"]

[upstream]
license = "WTFPL"
website = "https://remotestorage.io/"
code = "https://github.com/remotestorage/armadietto"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "500M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.is_signup]
    ask.en = "Allow signups?"
    ask.fr = "Accepter les inscriptions ?"
    help.en = "Would you like to allow visitors to register and create an account?"
    help.fr = "Souhaitez-vous autoriser les visiteurs à s'inscrire et créer un compte ?"
    type = "boolean"
    default = false

[resources]
    [resources.sources.main]
    # NOT used in install script, only for autoupdate
    url = "https://github.com/remotestorage/armadietto/archive/refs/tags/v0.6.0.tar.gz"
    sha256 = "8812fcd2271c00a6f23be929683427ed62ef1e5811668988f65d5896e888b72e"
    prefetch = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.needs_manual_tweaks = true

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["storage"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8008
