#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If is_signup doesn't exist, create it
if [ -z "$is_signup" ]; then
    is_signup="true"
    ynh_app_setting_set --key=is_signup --value=$is_signup
fi

# Remove old log file
ynh_safe_rm "/var/log/$app/"

#=================================================
# UPGRADE ARMADIETTO
#=================================================

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed; then
    ynh_script_progression "Upgrade armadietto with npm..."

    pushd "$install_dir"
        upstream_version=$(ynh_app_upstream_version)
        ynh_hide_warnings npm -g i "armadietto@$upstream_version"
    popd
fi

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"
chmod -R o-rwx "$data_dir"
chown -R "$app:$app" "$data_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

# Define armadietto module path
module_path="$node_version_path/$nodejs_version/lib/node_modules/armadietto/lib"

ynh_config_add --template="server.js" --destination="$install_dir/server.js"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add $app --description="Armadietto run a remotestorage server as service" --log="/var/log/$app/$app.log"

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
